### ISSUE TITLE
Vessel segmentation code

### ISSUE THREAD

**Issue by H-CODE6** [EmmaW8/Dofe#6]
Dear author, thank you very much for opening up this project. We have carefully studied your article and found that you also segmented the vessel area in the article, but this part of the code was not developed in this project. Can you open source this part of the code? Thank you very much, looking forward to your reply!

**Comment by emma-sjwang** [comment]
Thanks a lot for your interest and support on this project.
However, this project is no longer updated anymore due to code-related ethics issues.

I believe that the vessel segmentation-related parts are exactly the same as the OC/OD segmentation task except for the image and ground truth loading. This means you only need to rewrite the data loader part and segmentation masks prediction/loss calculation.

**Comment by H-CODE6** [comment]
Thank you very much for your reply. May I ask where the validation data you used during the training process to evaluate performance and save the trained model comes from? We look forward to your reply！
